version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "15306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: seonikjjang
      MYSQL_DATABASE: proj1
      MYSQL_USER: seonik
      MYSQL_PASSWORD: seonikjjang
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .               # 이 폴더(project root)에서 Dockerfile.app 사용
      dockerfile: Dockerfile.app
    container_name: profilenpoint-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/proj1
      SPRING_DATASOURCE_USERNAME: seonik
      SPRING_DATASOURCE_PASSWORD: seonikjjang

volumes:
  mysql_data: